# ===== Neon PostgreSQL connection =====
spring.datasource.url=jdbc:postgresql://ep-young-lab-adh2vfc1-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BJ0hV2CIPXzy

# ===== Hibernate JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Connection Pool =====
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

server.port=${PORT:8080}
